apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-app-ingress
  namespace: ruby-rails
spec:
  rules:
    - host: simplerailsapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rails-app
                port:
                  number: 3000
